### PR TITLE
Improve performance of the Dashboard

### PR DESCRIPTION
**Pull request by brecriffs**
## Description
In order to address long rendering times on the dashboard, I did the following, in order of effectiveness:

1. Initialise all charts', their axis's, legends, and any other static components, only once, inside componentDidMount. Data for each chart is compiled and added to each chart in componentDidUpdate. 

2. Moved ```<MeetingList/>``` to its own folder and attached to redux. This was a good idea anyway I think, because MeetingList was starting to inherit a lot of props from its parent, ```<DashboarView/>```. But also, the prop ```areAllGraphsRendered``` was only needed in ```<MeetingList/>```.

3. Added shouldComponentUpdate to the ```<MeetingListElement/>```'s. If the list item wasn't selected or de-selected, it has no reason to re-render. This had pretty significant results. Also, we should consider lazy-loading this list in the future.

4. Move styled from Styled components to Sass. This had a minor effect, but was seemingly a 3% improvement in render time.

**TODO**
There seems to be a UI freeze after you select a meeting. This is probably during the period when amcharts is directly manipulating the DOM. This is a more complex issue to solve, and Mike thinks he has some ideas. We will address this in the future.

## Motivation and context
rifflearning/zenhub#225

## How has this been tested?
Tested locally on Chrome and Firefox. This branch has also been on dev, where I did further testing. 

## Types of changes
- ✅ Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**

### CODE REVIEW

**Comment by mlippert** [comment]
Hmm, I haven't looked at any code yet, but from the description on this PR, it sounds like the MeetingList has some dependency on all the graphs being rendered? That is backwards. The MeetingList shouldn't care what the graphs do. It is possible that the graphs may care if a new meeting is selected while they are still in the process of rendering a previously selected meeting.

Anyway just my 1st thought on this PR

**Comment by brecriffs** [comment]
> Hmm, I haven't looked at any code yet, but from the description on this PR, it sounds like the MeetingList has some dependency on all the graphs being rendered? That is backwards. The MeetingList shouldn't care what the graphs do. It is possible that the graphs may care if a new meeting is selected while they are still in the process of rendering a previously selected meeting.
> 
> Anyway just my 1st thought on this PR

My motivation for this was: Due to UI freeze, scrolling of the MeetingList is temporarily blocked, and the blocking is relieved somewhere around when the graphs are rendered. Also, it might be nice to have a loader replacing the Meeting that you clicked on, indicating the dashboard is still rendering the metrics for that meeting.

**Comment by mlippert** [comment]
force pushed to merge commits that were only to fix issues w/ previous changes back with those changes
I'm not sure what or why Brec was encountering issues w/ relative imports of a directory, but it works fine for me now, so I changed that back.

**Comment by mlippert** [comment]
**Release** [gt-1.0.0-dev.6](https://github.com/rifflearning/riff-rtc/releases/tag/gt-1.0.0-dev.6)

**Pull request merged**
