### PR TITLE
Fix metrics text overflow bug

### PR DESCRIPTION
**Pull request by brecriffs**
## Description
When there is insufficient data, both influence charts display some text to tell the user that there isn't enough data. As you reduced the browser width, this text overflowed. To address this, I set a minimum height of 200px on the charts and reduced the left and right padding around the text when the browser width is below 1070px. I also introduced the flex model to the text, to keep it centered within the graph.

## Motivation and context
rifflearning/zenhub#195

## How has this been tested?
Tested locally on Chrome (Version 77.0.3865.90), Ubuntu 18. 

## Screenshots (if appropriate):
Browser width of 1024px and showcasing min-height:
Screenshot from 2019-10-14 11-42-26

## Types of changes
- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**

### CODE REVIEW

**Comment by mlippert** [comment]
rebased to head of develop

**Comment by brecriffs** [comment]
> Pushed a new commit that removed the OneThirdChart styled component (see comment in commit) and renamed the `GraphDefaultText` to `EmptyGraphText`
> 
> @brecriffs Let me know if we should discuss this. I think we already did though.

Looks good. Yes we did discuss this. Seems like we might revisit this when we work on the 'flexible and extendable dashboard'. But for now, this does make it more obvious what is happens with the columns.

**Comment by mlippert** [comment]
force pushed to rebase to head of develop

**Comment by mlippert** [comment]
**Release** [1.2.0-dev.21](https://github.com/rifflearning/riff-rtc/releases/tag/1.2.0-dev.21)

**Pull request merged**
