### PR TITLE
fix gantt x-axis ticks from dashboard refactor

### PR DESCRIPTION
**Pull request by mlippert**
## Description
The bug was caused during the refactor when I merged the code setting the ticks in the constructor into the _initAxis method which was overriding what had been done in the constructor. The previous code ended up letting d3 decide for itself what ticks to display.

I think this is better than it was before the refactor, because I'm specifying the ticks based on
the meeting duration.

There is still something odd going on in that most of the time a tick and/or tick label for the start
and end of the chart is not shown despite it being specified.

Also I noticed while testing this that the meeting duration I calculated based on the utterances to be
displayed is usually shorter, sometimes much shorter than what the Meeting Info on the dashboard says.

## Motivation and context
This is fixing a bug introduced by the dashboard refactor.

## How has this been tested?
Tested locally on my development machine.

## Types of changes

- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:

- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**

### CODE REVIEW

**Comment by mlippert** [comment]
force pushed changing the debug log prefix from gantt to Gantt to match the other debug logging in the file.

**Comment by mlippert** [comment]
**Release** [1.2.0-dev.10](https://github.com/rifflearning/riff-rtc/releases/tag/1.2.0-dev.10)

**Comment by adonahue** [comment]
** Testing Notes **
These behaviors looked like "bugs" but have been replicated in https://beta.riffplatform.com/ indicating that they were not introduced as part of this refactor or fix. Noting here for the record. 

- [ ] Timeline usually displays in 5 minute increments but not always. If a conversation was brief, it will subdivide into smaller units. From a two minute meeting on Beta: 

 - [ ] The time in the navigation is significantly off from the times on the gant chart. Gant chart for a meeting at 9AM JUN 6TH, on Beta: 


** Not Replicated, to Fix ** 
@mlippert 
- [ ] The start and end marks of the meeting, in a time that is sometimes different than the units for the rest of the scale, now display as the tick marks right next to the apoening and closing tick marks on the gant chart. To replicate the previous behavior, the start and end lines should not have any values, and the start and end times should not be displayed.  
Staging behavior:

Expected behavior (from Beta):


- [ ] Gant chart timeline does not match meeting time; I could not replicate this in Beta. The meeting time below has a gant count of 35 minutes, but lists 85 minutes as meeting duration, both in the meeting summary and the speaking time. The gant chart scale should total the meeting duration.

**Comment by mlippert** [comment]
I'm not sure I agree that anything should be changed, I've addressed your issues w/ my thoughts below for further discussion.

- [ ] I adjust the tickmark time based on the duration spanned by the chart, figuring it is better to see some ticks than none. That's why short meeting have ticks 2 minutes apart and longer meetings have tickmarks spread further apart. The actual demarcations where that time changes is:

- duration < 15 minutes - 2 minutes
- duration < 40 minutes - 5 minutes
- duration < 80 minutes - 10 minutes
- anything longer 15 minutes

I don't easily have total control over the timeline tickmarks, I can set it back to just letting d3 decide for itself, but that is what gave us timelines with no tick values at all, and I personally think the current behavior is better.

- [ ] The times in the tick marks on the timeline are from the data, the fact that the meeting says it started at an earlier time than the 1st person actually spoke is just what it is. However keep in mind the discrepancy may not be as large as it appears, that meeting that you think started at 9am, may have actually started at 9:59am

- [ ] The time at the start and end isn't in different units (it's still clock time) it just isn't spread out the same as the rest of the ticks. I did this deliberately because I really think that knowing the actual start and end times of the chart is important.

- [ ] The timeline chart displays the data, I can't make it display data that doesn't exist. I can try to get the database and examine the data for a particular meeting that you think is wrong in order to check if the timeline data is no longer being processed correctly.

**Comment by adonahue** [comment]
Start and end times no longer display. A user-friendly scale (2, 5, 10, or 15 minute increments) is layered on top of the timeline data. Often these ticked increments display in a distributed way, but sometimes start or end of a meeting is offset from the scale. This functionality is equivalent to the auto-drawn ticks, prior to the refactor, and improved in that it does not display a scale of seconds as minutes, which is confusing and looks broken.

**Pull request merged**
