### PR TITLE
Start scss refactoring as an example

### PR DESCRIPTION
**Pull request by brecriffs**
## Description
Using the SCSS 7-1 approach. I have started to refactor the SCSS for riff-rtc. Info on this approach can be found here:
https://sass-guidelin.es/#the-7-1-pattern

In order to demonstrate this architectural approach, I took all styles from src/index.scss and placed them in the appropriate style directory and file. Some in temporary directories/files. For example, styles for the chartcard.jsx, were put in a general file called _dashboard.scss for now...until we have settled on a folder structure and refactored the dashboard components completely.

## Motivation and context

https://app.zenhub.com/workspaces/riff-projects-5cb6029b4103d93ceadf001b/issues/rifflearning/riff-rtc/110

## How has this been tested?

Tested locally to ensure that styles were being applied the same as before this branch.

## Types of changes

- ✅ New feature (non-breaking change which adds functionality)

## Checklist:

- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**

### CODE REVIEW

**Comment by brecriffs** [comment]
Also, I have not removed some commented out lines in styles that I took from index.scss. I figured once we settle on an architecture, it would then make sense to really clean up what styles are there, and what styles are redundant and/or unused.

**Comment by mlippert** [comment]
From our previous discussions I was expecting something more like what is described briefly here:
https://blog.jamigibbs.com/getting-sass-running-quickly-in-your-react-webpack-project/

Where each component implemented in a .jsx file has a sibling file .scss file that it imports.

This may be a poor way to structure things.

**Comment by brecriffs** [comment]
> From our previous discussions I was expecting something more like what is described briefly here:
> https://blog.jamigibbs.com/getting-sass-running-quickly-in-your-react-webpack-project/
> 
> Where each component implemented in a .jsx file has a sibling file .scss file that it imports.
> 
> This may be a poor way to structure things and the 7-1 approach may be much better, I don't know.

My task was to make a general recommendation as to how I would approach styling. I have reviewed that article, and it is definitely another way to go. However, I like keeping the styling separate from the React components. There are pro's and con's to both approaches. 

A potential con of using the method you shared, is having to spend time having to optimise the SASS imports, as I believe they will become part of the JS bundle. A pro is, the styles in each SCSS file will automatically be made available to only the components that import it. A potential downside to this is, you may end up having to import several SCSS files into a component. If you need styles from, for example, a base.scss, somepage.scss, and thiscomponent.scss. Using the 7-1 approach (or in general, just separating the SCSS from the react components), requires taking a closer look at the scope of your styles, since the stylesheets will be available globally to all components. A common technique is using BEM naming conventions (More information here: https://css-tricks.com/using-sass-control-scope-bem-naming/). My general recommendation is to use the 7-1 technique, while keeping in mind the scope of each style, and avoiding using webpack all together. Perhaps @jordanreedie would like to flex his front-end skills/experience here a little bit, and maybe share what his thoughts are. The strategy that we choose to go with now will most likely be used for a long time, so it makes sense to really hash this out.

**Comment by brecriffs** [comment]
@mlippert Rebased and added header to main.scss.

**Comment by mlippert** [comment]
@brecriffs You're still planning on adding headers to the other scss files, right?

**Comment by brecriffs** [comment]
> @brecriffs You're still planning on adding headers to the other scss files, right?

I can. I thought I remembered you saying 'We should add headers to the scss files, or at least the main scss file'. Either way, it might be nice to have them in each partial. I will add that.

**Comment by brecriffs** [comment]
@mlippert Added headers to all scss files

**Comment by mlippert** [comment]
The year in the header comments was off, so I fixed it (it was 2018 instead of 2019 an easy typo to make).

I'm going to squash the 3 commits and merge them (the differences between the commits isn't worth remembering)

**Comment by mlippert** [comment]
**Release** [1.2.0-dev.12](https://github.com/rifflearning/riff-rtc/releases/tag/1.2.0-dev.12)

**Pull request merged**
