### PR TITLE
add some error logging to catch when peers get assigned duplicate colors

### PR DESCRIPTION
**Pull request by mlippert**
## Description
Changed the code which creates the PeerVideos in order to add error logging to
catch when a peer gets assigned the same color as a different peer.
In particular log errors when the peer's riffId either is not found in the list of
riffIds or when a previous peer had the same riffId (which is how a duplicate
color would get assigned).

## Motivation and context
It's not clear why sometimes peers in a video chat are getting assigned the same
color.

## How has this been tested?
tested on my local machine to see that chat still works with 2 participants

## Types of changes

- ✅ Bug fix (non-breaking change which fixes an issue) (Well helps debug an issue)

## Checklist:

- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**

### CODE REVIEW

**Comment by mlippert** [comment]
force pushed because I noticed and removed some comments that were no longer true.

**Comment by iamtomhanks** [comment]
@mlippert Looks good to me! `peerVideo()` function seems like it could be removed completely now.

**Comment by mlippert** [comment]
@iamtomhanks You're right, and I considered it while I was doing this, but wasn't sure there might not be some reason to keep it around (either because we may want it again once we figure out more, or because it's more in keeping w/ react style, which I'm not all that familiar with).
Thanks for the review. We should keep in mind either removing the `peerVideo` method or moving all of that functionality that's in the nested map function to it so we don't need such a large nested function.

But I'm going to get this merged so we can start having debugging information in the console log.

**Comment by mlippert** [comment]
[Color map does not consistently assign colors, or unique colors to each participant](https://trello.com/c/98GSzEh9/270-color-map-does-not-consistently-assign-colors-or-unique-colors-to-each-participant)

**Pull request merged**
