### PR TITLE
Fix/misc fixes

### PR DESCRIPTION
**Pull request by dcalacci**
various fixes:

- room name population for LTI users
- text chat correctly displays full names for users 
- new chat state that has been cleared does not get a badge
- sorting participants sent to timeline chart to make sure color is correct

## Types of changes

- ✅ Bug fix (non-breaking change which fixes an issue)
- ✅ New feature (non-breaking change which adds functionality)
- ✅ Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ My change requires a change to the documentation and I have updated it accordingly.
- ✅ I have added tests to cover my changes.

### CODE REVIEW

**Comment by mlippert** [comment]
@dcalacci Why is it necessary to populate the room name on chat component if the user is LTI?

If the user is LTI, the room name should have already been populated on load (in the App WillMount by calling the `loginLTIUser` action creator. How did you get to a point where you had an LTI user and the room name wasn't set?

**Comment by dcalacci** [comment]
@mlippert If a user refreshes the page while in a videochat, the room name is set to not persist (across all use cases), which means that the room name field in the lobby will be empty, but also not edit-able (because the user is LTI). That change simply populates roomName from the lti state if our store thinks the user is logged in via LTI

**Comment by mlippert** [comment]
@dcalacci Thanks and gotcha. It's helpful to know what path causes this fix to be needed.

**Comment by dcalacci** [comment]
if you're OK merging this i'd like to get it into staging today! thank you mike!

**Comment by mlippert** [comment]
Sure, not a problem. I didn't want to do anything until you asked.

**Comment by dcalacci** [comment]
[meeting colors wrong in timeline object on dashboard](https://trello.com/c/hW6Ub21C/118-meeting-colors-wrong-in-timeline-object-on-dashboard)

**Pull request merged**
