### PR TITLE
Feature/influence bar graphs

### PR DESCRIPTION
**Pull request by dcalacci**
bar graphs for "influence" rather than a network diagram

## How has this been tested?
tested locally with users on separate networks and different browsers

- ✅ New feature (non-breaking change which adds functionality)

## Checklist:
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**

### CODE REVIEW

**Comment by jordanreedie** [comment]
sweet! I was just about to submit a PR for the changes I made but if this addresses it then I'll hold off

**Comment by jordanreedie** [comment]
I noticed that the getusermedia constraints are still `max` instead of `ideal` here, but on dev.riffedu.com they have been changed - is that a separate code base?

**Comment by jordanreedie** [comment]
Also, the scrolling changes look good to me on chrome 👍  

I think amy / beth were interested in having the nav bar pinned to the top of the screen (which iirc is the way it behaved before?), thoughts?

**Comment by mlippert** [comment]
Let me know when this is done being reviewed and is ready to be merged (you can assign it to me).

**Comment by dcalacci** [comment]
@jordanreedie might be that on merge it should be `ideal`. 

@jordanreedie RE navbar -- I don't think the nabber was ever sticky, but I get why it might be helpful here. I can look into how to do it in bulma.

**Comment by jordanreedie** [comment]
@dcalacci ah, it wasn't implemented as a sticky, but the divs w/ the charts and list of meetings were the ones that scrolled instead of the page, so it gave the appearance of it

the actual scrolling works though, so i think its fine? your call i guess

**Comment by dcalacci** [comment]
"nabber".

sticky is more work so I'll leave it be for now

**Comment by dcalacci** [comment]
@mlippert ready to merge

**Pull request merged**
