### PR TITLE
Enable user zooming and scaling for a11y improvement

### PR DESCRIPTION
**Pull request by iamtomhanks**
## Description
Removed `user-scalable="no"` from meta tag in /public/index.html

## Motivation and context
Enables text scaling and zooming for improved accessibility. 
https://trello.com/c/L7JQT6m3/239-zooming-and-scaling-disabled

## How has this been tested?
Tested locally.
Will need to test on mobile device to determine effects.

2018-12 Riff Learning Accessibility Audit [Item 9](https://docs.google.com/spreadsheets/d/1fya1fMKkVKKWhF0HjIMhJxsZt-S0nq2-ATxtUT3MfT0/edit#gid=990583410&range=B10)

## Types of changes
- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**

### CODE REVIEW

**Comment by iamtomhanks** [comment]
Was there a motivation for adding `user-scalable="no"`? This should be tested on different mobile devices/browsers.

**Comment by iamtomhanks** [comment]
[Zooming and scaling disabled](https://trello.com/c/L7JQT6m3/239-zooming-and-scaling-disabled)

**Comment by jordanreedie** [comment]
> Was there a motivation for adding `user-scalable="no"`? This should be tested on different mobile devices/browsers.

I'm not sure what the motivation was for adding it. Just noting that as far as I know nothing has ever been tested for mobile devices + we do not support them currently (and i'm not sure if that's even on the roadmap right now)

**Comment by mlippert** [comment]
Just wanted to say, thanks for the question and the responses.

**Pull request merged**
